-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Dec 14, 2022 at 01:49 PM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `clee84_dmit2025`
--

-- --------------------------------------------------------

--
-- Table structure for table `top_books_rd`
--

CREATE TABLE `top_books_rd` (
  `title` varchar(255) NOT NULL,
  `author` varchar(75) NOT NULL,
  `synopsis` text DEFAULT NULL,
  `publisher` varchar(60) NOT NULL,
  `genre_drama` varchar(2) NOT NULL DEFAULT '0',
  `genre_sciencefiction` varchar(2) NOT NULL,
  `genre_horror` varchar(2) NOT NULL,
  `genre_mystery` varchar(2) NOT NULL,
  `genre_romance` varchar(2) NOT NULL,
  `genre_historicalfiction` varchar(2) NOT NULL,
  `genre_fantasy` varchar(2) NOT NULL,
  `genre_poetry` varchar(2) NOT NULL,
  `genre_realistnovel` varchar(2) NOT NULL,
  `genre_autobiography` varchar(2) NOT NULL,
  `genre_nonfiction` varchar(2) NOT NULL,
  `publication` int(4) NOT NULL,
  `length` int(5) NOT NULL,
  `award` varchar(60) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `img_filename` varchar(100) NOT NULL,
  `book_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `top_books_rd`
--

INSERT INTO `top_books_rd` (`title`, `author`, `synopsis`, `publisher`, `genre_drama`, `genre_sciencefiction`, `genre_horror`, `genre_mystery`, `genre_romance`, `genre_historicalfiction`, `genre_fantasy`, `genre_poetry`, `genre_realistnovel`, `genre_autobiography`, `genre_nonfiction`, `publication`, `length`, `award`, `url`, `img_filename`, `book_id`) VALUES
('Anna Karenina', 'Leo Tolstoy', 'Ah, Anna Karenina. Lusty love affair or best romance of all time? Most critics pin it as one of most iconic literary love stories, and for good reason. Leo Tolstoyï¿½s sweeping Russian tale of star-crossed lovers is littered with swoon-worthy quotes like, ï¿½He stepped down, trying not to look long at her, as if she were the sun, yet he saw her, like the sun, even without looking.ï¿½ Described by Fyodor Dostoevsky as ï¿½flawless,ï¿½ this one belongs on any book collectorï¿½s shelf.', 'The Russian Messenger', '', '', '', '', '1', '', '', '', '1', '', '', 1878, 864, '', 'https://www.youtube.com/watch?v=Z-nyXX5zOLg', 'anna-karenina.jpeg', 1),
('To Kill A Mockingbird', 'Harper Lee', 'Harper Lees To Kill a Mockingbird upends the quiet solitude of a segregated Southern town with a story of innocence and virtue, bigotry and hate, love and forgiveness. Eight-year-old Scout Finch and her father, Atticus, find themselves enmeshed in the trial of a Black man accused of raping a White woman. In one of the most deeply sad books, Lee tells the events, revelations, and lessons through the eyes of a young child. Widely read and widely taught, To Kill a Mockingbird continues to spark discussions of race in classrooms and libraries across the country.', 'J. B. Lippincott & Co.', '', '', '', '', '', '1', '', '', '', '', '', 1960, 281, '', 'https://www.youtube.com/watch?v=KR7loA_oziY', 'to-kill-a-mockingbird.jpeg', 2),
('Where The Sidewalk Ends', 'Shel Silverstein', 'The imagination and artistry of Shel Silverstein are on full display in this classic collection of short stories and poems. Where the Sidewalk Ends is truly one of the best poetry books of all time because of its staying power for children and adults alike. Whimsical and masterful, the stories of this American poet, author, singer, and folk artist have something for everyone.', 'Harper and Row Publishers', '', '', '', '', '', '', '', '1', '', '', '', 1974, 309, '', NULL, 'where-the-sidewalk-ends.jpeg', 3),
('Valley of the Dolls', 'Jacqueline Susann', 'Sex and drugs have a common allure, but they also have a common endgame: a downward spiral. In Valley of the Dolls, Jacqueline Susann offers in lurid detail the stories of three young women who want nothing more than to reach the pinnacle of life. But just as they see it in their grasp, they lose it all in a coil of sex, lust, romance, and abandonment. This page-turner is one of those classic beach reads you wonâ€™t be able to put down, and it paved the way for similar scintillating vacation books.', 'Bernard Geis Associates', '', '', '', '', '', '', '', '', '1', '', '', 1966, 422, '', NULL, 'valley-of-the-dolls.jpeg', 4),
('The Shining', 'Stephen King', 'The master of suspense must be included in any list of books you should read in a lifetime. Thatâ€™s why youâ€™ll find Stephen Kingâ€™s The Shining here. Brought to life in cinematic perfection by Jack Nicholson, Jack Torrance is a middle-aged man looking for a fresh start. He thinks heâ€™s found it when he lands a job as the off-season caretaker at an idyllic old hotel, the Overlook. But as snow piles higher outside, the secluded location begins to feel more confining and sinister, less freeing and more provoking. Horror fans, take note: This is one of the scariest and best Stephen King books of all time.', 'Doubleday', '', '', '1', '', '', '', '', '', '', '', '', 1977, 447, '', 'https://www.youtube.com/watch?v=5Cb3ik6zP2I', 'the-shining.jpeg', 5),
('The Little Prince', 'ntoine de Saint-ExupÃ©ry', 'The Little Prince is a timeless tale of a princeâ€™s journey from planet to planet in search of adventure. What he finds, however, are interactions with adults who leave him frustrated or dismayed. In the Sahara Desert, he runs into the bookâ€™s narrator, and the two start an eight-day journey filled with lessons. Donâ€™t let this bookâ€™s size fool youâ€”itâ€™s one of the most compelling short books weâ€™ve ever read. Itâ€™s also one of the most widely read classics all over the world. Whether you prefer reading in English, French, or another language, youâ€™re bound to find a copy.', 'Reynal & Hitchcock', '', '', '', '', '', '', '1', '', '', '', '', 1943, 96, '', 'https://www.youtube.com/watch?v=fEPqgSNLfK8', 'the-little-prince.jpeg', 6),
('The Fellowship of the Ring', 'J.R.R. Tolkien', 'In The Fellowship of the Ring, the first book in the Lord of the Rings trilogy, journey to Middle-earth and into the world of Frodo Baggins, Samwise Gamgee, Gandalf the Grey, the dark lord Sauron, and the entire assemblage of Tolkienâ€™s most famous characters and story lines. Frodo is tasked with destroying the One Ring, the most powerful Ring in Mordor, but along the way, his quest is filled with many of Tolkienâ€™s unique and captivating characters, as well as an adventure of epic proportions. Though the world of Middle-earth is entirely made up, the trilogy teases out universal themes of good versus evil that have resonated with readers of all ages and backgrounds. Itâ€™s widely regarded as one of the best fantasy books of all time and a must-read for lovers of the genre.', 'George Allen & Unwin', '', '1', '', '', '', '', '1', '', '', '', '', 1954, 423, '', 'https://www.youtube.com/watch?v=V75dMMIW2B4', 'the-fellowship-of-the-ring.jpeg', 7),
('The Handmaid\'s Tale', 'Margaret Atwood', 'Offred, a handmaid in the Republic of Gilead, has been removed from the home, family, and life that she knew only to be forced into service as a housemaidâ€”and a working pair of ovaries. As the population of Gilead falls, a womanâ€™s value becomes contingent upon her fertility and ability to reproduce, and those who can procreate are stripped of their independence. Margaret Atwoodâ€™s The Handmaidâ€™s Tale is one part cautionary tale and one part enthralling narrative. Though written decades ago, it remains chillingly compelling for our time as was proven by audience reactions to itâ€™s on-screen adaptation. While Season 6 of The Handmaidâ€™s tale is yet to be released, you can binge the rest of the show on Hulu if you like both watching and reading. Thereâ€™s a reason Readerâ€™s Digest counts it among the best feminist books.', 'McClelland and Stewart Houghton Mifflin Harcourt', '', '1', '', '', '', '', '', '', '', '', '', 1985, 311, '', 'https://www.youtube.com/watch?v=dVLiDETfx1c', 'the-handmaids-tale.jpeg', 8),
('A Wrinkle in Time', 'Madeleine Lâ€™Engle', 'While this book may have seen an uptick in interest thanks to the 2018 film starring Oprah Winfrey, Mindy Kaling, and Reese Witherspoon, Madeleine Lâ€™Engleâ€™s A Wrinkle in Time has long been held as a must-read for its fantastical telling of splitting the fabric of time and space. A Newbery Medal winner, this science-fantasy novel follows troublesome and stubborn Meg Murry as she confronts her fatherâ€™s mysterious disappearance with a collection of peculiar neighbors: Mrs. Whatsit, Mrs. Who, and Mrs. Which. Elements of love, trust, and overcoming fear are woven into this enchanting coming-of-age story. We always recommend reading the book before pressing â€œplay,â€ so once youâ€™ve thoroughly devoured this story, check out the other stellar books made into movies.', 'Ariel Books', '', '1', '', '', '', '', '1', '', '', '', '', 1962, 256, 'newbery', 'https://www.youtube.com/watch?v=UhZ56rcWwRQ', 'a-wrinkle-in-time.jpeg', 9),
('Pride and Prejudice', 'Jane Austen', 'Jane Austenâ€™s classic Pride and Prejudice adorned shelves of many a learned reader in the 1800s and 1900s, but its timeless story and lessons earn it a spot in many home libraries (and on many school reading lists) even today. When eligible young men arrive in their neighborhood, Mr. and Mrs. Bennett must prepare their five eager daughters for the role of a lifetime: wife. While the Bennett sistersâ€™ wit and humor keep the pages flipping, the classic story, which is widely considered one of the best romance novels, also serves as a harbinger for hasty mistakes and erred judgments.', 'T. Egerton, Whitehall', '', '', '', '', '1', '', '', '', '', '', '', 1813, 432, '', 'https://www.youtube.com/watch?v=1dYv5u6v55Y', 'pride-and-prejudice.jpeg', 10),
('All the President\'s Men', 'Bob Woodward and Carl Bernstein', 'Political junkies of all stripes will relish the words of Washington Post reporters Bob Woodward and Carl Bernstein as they recount the experiences and events of Watergate. Published just months before President Richard Nixonâ€™s 1974 resignation, the book outlines all the evidence against Nixon and his cohort of political operatives that the two accomplished reporters unearthed during their investigations. It also marks the genesis of Deep Throat (later revealed to be Mark Felt, the associate director of the FBI), the secretive government informant who helped take down Nixon in the end.', 'Simon & Schuster', '', '', '', '1', '', '', '', '', '', '', '', 1974, 400, 'pulitzer', 'https://www.youtube.com/watch?v=DC3YFyah_Yg', 'all-the-presidents-men.jpeg', 11),
('Man\'s Search for Meaning', 'Viktor E. Frankl', 'Between 1942 and 1945, Viktor Frankl labored in four Nazi death camps. His parents, brother, and pregnant wife perished. Later in life, Frankl became a psychiatrist and practiced what he coined logotherapy, a theory that our lives are primarily driven by the discovery and pursuit of what we find meaningful. In Manâ€™s Search for Meaning, Frankl shares the horrors he faced in those concentration camps. But in this extraordinary Holocaust book, he also shares the lessons he learnedâ€”and later taught his patientsâ€”about spiritual revival in the face of such great suffering.', 'Beacon Press', '', '', '', '', '', '', '', '', '', '1', '', 1946, 200, '', NULL, 'mans-search-for-meaning.jpeg', 12),
('Beloved', 'Toni Morrison', 'Toni Morrisonâ€™s Beloved stares down the horrors of slavery and transforms a narrative you think youâ€™ve read a hundred times into a towering tale of pain, agony, triumph, and freedom. The story of Sethe, the novelâ€™s protagonist, is gut-wrenchingly honest and simultaneously beautiful and hideous. She wears the worries of past decisions and strives longingly toward freedom, the arc for which her entire life story bends. The suspense wears heavy on the reader, and the choices you must weigh alongside Sethe are haunting. The book is a cultural landmark for breaking through the monotony of textbook descriptions and offering a human glimpse at a shameful season in history.', 'Alfred A. Knopf Inc.', '', '', '', '', '', '1', '', '', '', '', '', 1987, 324, 'pulitzer', 'https://www.youtube.com/watch?v=RAsnKghD2uw', 'beloved.jpeg', 13),
('In Cold Blood', 'Truman Capote', 'On Nov. 15, 1959, the small town of Holcomb, Kansas, was turned on end by the savage murder of four members of the Clutter family. The police had no suspects and almost no evidence. Truman Capoteâ€™s book In Cold Blood recounts in chilling detail the deaths of the family and the investigation that ultimately led to the arrest of two recently paroled ex-convicts. Capoteâ€™s work may be a story stuck in time, but its nonfiction narrative reveals a lot about violence and evil that resonates even today. This is often considered a model for the best true crime books, regardless of the time period.', 'Random House', '', '', '', '', '', '', '', '', '', '', '1', 1965, 343, '', 'https://www.youtube.com/watch?v=vU_TY9ZQ48A', 'in-cold-blood.jpeg', 14),
('A Long Way Gone: Memoirs of a Boy Soldier', 'Ishmael Beah', 'Itâ€™s a story so painful, youâ€™d prefer to think it is fiction. But Ishmael Beahâ€™s A Long Way Gone is an entirely true recounting of his years as a child soldier in Sierra Leone, West Africa. With this book, youâ€™ll get a firsthand look at what life is like for the worldâ€™s 300,000 child soldiers, many of whom are stolen from their homes and forced into a world of drugs, guns, and murder. In a world made small by 24-hour news and lightning-speed technology, this is a must-read for understanding the plight of fellow humans.', 'Sarah Crichton Books', '', '', '', '', '', '', '', '', '', '1', '1', 2007, 240, '', NULL, 'a-long-way-gone-memoirs-of-a-boy-soldier.jpeg', 15),
('Dune', 'Frank Herbert', 'A science fiction novel for the ages, Frank Herbertâ€™s Dune tells the adventures of Paul Atreidesâ€”who will become known as Muadâ€™Dibâ€”as he and his family strive to bring humankindâ€™s greatest dream to life while living on a desert planet. Though written in 1965, much of Duneâ€˜s story may be more relevant to 21st-century readers than it was to bookworms who picked it up in the â€™60s. It has sparked countless other works in the collection of stellar science fiction books.', 'Chilton Books', '', '1', '', '', '', '', '', '', '', '', '', 1965, 412, '', 'https://www.youtube.com/watch?v=n9xhJrPXop4', 'dune.jpeg', 16),
('Great Expectations', 'Charles Dickens', 'When Charles Dickens wrote Great Expectations, he gave life to some of literatureâ€™s most colorful and enduring characters: Pip, Miss Havisham, and Uncle Pumblechook, to name a few. His penultimate novel, Great Expectations details the life and stories of an orphan named Pip, growing up in Kent and London in the early to mid-1800s. Itâ€™s a classic and a must-read quite simply because itâ€™s been described as one of Dickensâ€™ best works, an appraisal to which Dickens himself agreed.', 'Chapman & Hall', '', '', '', '', '', '1', '', '', '', '', '', 1861, 544, '', 'https://www.youtube.com/watch?v=Q9RUEgT9zcc', 'great-expectations.jpeg', 17),
('1984', 'George Orwell', 'George Orwell certainly couldnâ€™t have known how prophetic his words might have been when he wrote the dystopian novel 1984 in the mid-20th century. Great Britain has fallen and given way to Airstrip One, a province of the fictional superstate Oceania. Airstrip One is ruled by perpetual war and Big Brother, a mysterious leader who uses omnipresent government surveillance and a cult of personality to enforce law and order. Winston Smith, the bookâ€™s leading character, must navigate the Party, Big Brother, and his thoughts, which grow more criminal by the day.', 'Secker & Warburg', '', '1', '', '', '', '', '', '', '', '', '', 1949, 328, '', 'https://www.youtube.com/watch?v=T8BA7adK6XA', '1984.jpeg', 18),
('Angelaâ€™s Ashes: A Memoir', 'Frank McCourt', 'In his Pulitzer Prizeâ€“winning novel, Angelaâ€™s Ashes, author Frank McCourt recounts his childhood spent in the slums of Limerick, Ireland: â€œWhen I look back on my childhood I wonder how I managed to survive at all. It was, of course, a miserable childhood: the happy childhood is hardly worth your while. Worse than the ordinary miserable childhood is the miserable Irish childhood, and worse yet is the miserable Irish Catholic childhood.â€ McCourt battled poverty, near-starvation, neglect, and cruelty but manages to tell his story with humor, compassion, and self-perpetuating power. His award-winning book is widely considered one of the best memoirs of all time.', 'Simon & Schuster', '', '', '', '', '', '', '', '', '', '1', '', 1996, 368, 'pulitzer', 'https://www.youtube.com/watch?v=NPXP17JJ4GY', 'angelas-ashes-a-memoir.jpeg', 19),
('A Brief History of Time', 'Stephen Hawking', 'Most science books, even well-written ones, read a bit too much like textbooks. But renowned English physicist, cosmologist, and author Stephen Hawking manages to turn some of the worldâ€™s most profound questionsâ€”How did the universe begin? What happens in the end?â€”into captivating reading. A modern physics guide, this book was perhaps the first to make the most mysterious elements of the universe (black holes and quarks) entirely accessible for the general public.', 'Bantam Dell Publishing Group', '', '', '', '', '', '', '', '', '', '', '1', 1988, 256, '', 'https://www.youtube.com/watch?v=Salz7uGp72c', 'a-brief-history-of-time.jpeg', 20),
('Fahrenheit 451', 'Ray Bradbury', 'Guy Montagâ€™s existence in Fahrenheit 451 might hit a little close to home: Heâ€™s a fireman in a futuristic dystopian world whose job is to find and destroy the illegal commodities of a world whose sole focus is television: books. Indeed, Montag believes the printed word is dangerousâ€”until a mysterious neighbor, Clarisse, shows up and opens his eyes to the wonder of the written word. This spellbinding story explores questions about the importance of literature and free speech. If you oppose banning books, this is the novel for you.', 'Simon & Schuster', '', '1', '', '', '', '', '', '', '', '', '', 1953, 256, '', 'https://www.youtube.com/watch?v=AeDBaMg8NSQ', 'fahrenheit-451.jpeg', 21),
('A Heartbreaking Work of Staggering Genius', 'Dave Eggers', 'First released in 2000, Dave Eggersâ€™ A Heartbreaking Work of Staggering Genius became a national best seller, a Pulitzer Prize finalist, and a heartwarming classic. This masterpiece is the memoir of a college senior whose life is turned upside down when he loses both of his parents within the span of five weeks and finds himself the guardian of his eight-year-old brother. Despite that ominous start, the book manages to be wildly funny with an irreverently honest take on learning to live with death.', 'Simon & Schuster', '', '', '', '', '', '', '', '', '1', '', '1', 2000, 375, '', NULL, 'a-heartbreaking-work-of-staggering-genius.jpeg', 22),
('Harry Potter and the Sorcererâ€™s Stone', 'J.K Rowling', 'Welcome to the wizarding world, muggles. In J.K. Rowlingâ€™s first installment of the beloved series, Harry Potter and the Sorcererâ€™s Stone, you will be introduced to many of the storyâ€™s most importantâ€”and entrancingâ€”characters: Harry, Hermione, Ron, Dumbledore, Hagrid, and more. But before you get settled into the fun of spells and potions, the action starts right away as Harry finds himself troubled by the feeling his destiny is intertwined with his past. This book landed on our list for its explosive popularity and deep impression on the fantasy genre, as well as its many memorable quotes that will stay with you.', 'Bloomsbury', '', '', '', '', '', '', '1', '', '', '', '', 1997, 223, '', 'https://www.youtube.com/watch?v=VyHV0BRtdxo', 'harry-potter-and-the-sorcerers-stone.jpeg', 23),
('Selected Stories, 1968â€“1994', 'Alice Munro', 'Alice Munro, one of the most prolific writers of the modern era, captures lifeâ€™s most honest feelings and moments in these 28 magnificent short stories. Winner of the Nobel Prize in Literature, this short story collection will never cease to surprise you with its eloquent story lines, captivating characters, and endlessly wonderful realism. Itâ€™s a book that belongs on any bibliophileâ€™s home bookshelf.', 'McClelland and Stewart', '', '', '', '', '', '', '', '', '1', '', '', 1996, 704, 'nobel', NULL, 'selected-stories-1968â€“1994.jpeg', 24),
('Invisible Man', 'Ralph Ellison', 'A winner of the National Book Award for fiction, Ralph Ellisonâ€™s first novel, Invisible Man, spent an admirable 16 weeks atop the New York Times best-seller list. Its early success is due in large part to the relatable nature of its narrator, a young, nameless Black man who has to navigate levels of 1950s American culture that are fraught with hate and bias. Eager for a place in time to call his own, the narrator finds that what he hopes for himself will ultimately remain elusive, just as the truth behind the events that surround him remains ambiguous. The 581-page tome is a bit much for younger readers, but you can still introduce them to issues of race and equality with these childrenâ€™s books about diversity.', 'Random House', '', '', '', '', '', '', '', '', '1', '', '', 1952, 581, 'national', NULL, 'invisible-man.jpeg', 25),
('Are You There, God? Itâ€™s Me, Margaret', 'Judy Blume', 'If you read this as an adolescentâ€”and considering itâ€™s often taught in schools, thereâ€™s a good chance you didâ€”itâ€™s time to reread Are You There, God? Itâ€™s Me, Margaret. Awkward and inelegant as they may be, sixth-grader Margaretâ€™s questions and quests (to grow bigger breasts, for example, while also seeking out her preferred religion) lead her to greater understanding and self-appreciation. The book will make you cringe as you recall your own experiences and desires to throw off the chains of childhood while budding into young adulthood. Itâ€™s a coming-of-age story that sparked dozens after it, but isnâ€™t the original always the best', 'Bradbury Press', '', '', '', '', '', '', '', '', '1', '', '', 1970, 149, '', NULL, 'are-you-there-god-its-me-margaret.jpeg', 26),
('One Hundred Years of Solitude', 'Gabriel GarcÃ­a MÃ¡rquez', 'According to the New York Times Book Review, this masterpiece by Gabriel GarcÃ­a MÃ¡rquez is â€œthe first piece of literature since the Book of Genesis that should be required reading for the entire human race.â€ One Hundred Years of Solitude recounts the evolution of an entire fictitious town, Macondo. Through tales of men and women, boys and girls, the authorâ€”father of the magical realism literary styleâ€”offers a striking picture of the heartbreaking beauty and pain of the human race. Though it also landed on our list of the best books by Latinx authors, its true place is here, among the best books of all time.', 'Editorial Sudamericana', '', '', '', '', '', '', '1', '', '1', '', '', 1967, 417, 'nobel', NULL, 'one-hundred-years-of-solitude.jpeg', 27),
('Catch-22', 'Joseph Heller', 'If all you know of this American literature classic is the colloquial expression about decision-making, pick up Catch-22 for a dark and comedic good read. Yossarian, a member of an Italian bomber crew during World War II, is desperate to excuse himself from the increasingly high number of suicidal missions his commanders force him and his servicemen to fly. The catch comes when he realizes the sinister bureaucratic rule, Catch-22, classifies him as saneâ€”and thus ineligible for reliefâ€”if he requests to be removed from duty. The book made waves as an anti-war anthem and representation of the individual versus society.', 'Simon & Schuster', '', '', '', '', '', '1', '', '', '', '', '', 1961, 451, '', 'https://www.youtube.com/watch?v=JARn16yojbQ', 'catch-22.jpeg', 28),
('The Autobiography of Malcolm X: As Told to Alex Haley', 'Malcolm X and Alex Haley', 'The Autobiography of Malcolm X stands as the definitive work of an era in American history when cultural, racial, and religious ideologies met at a pinnacle. Malcolm X, a firebrand, Muslim, and anti-integrationist leader, reveals the limits he sees in the American Dream and the changes that can be made through a force of will and effort. Fun fact: Coauthor Alex Haley was once an editor at Readerâ€™s Digest.', 'Grove Press', '', '', '', '', '', '', '', '', '', '1', '1', 1965, 460, '', NULL, 'the-autobiography-of-malcolm-x-as-told-to-alex-haley.jpeg', 29),
('Interpreter of Maladies', 'Jhumpa Lahiri', 'In this collection of short stories, Jhumpa Lahiri outlines the complex dynamics that exist when Indian traditionalism meets an American culture that often offers little respect for complex cultural dynamics it doesnâ€™t understand. Each characterâ€™s story traces recognizable themesâ€”longing, lust, betrayalâ€”but theyâ€™re told in a complex story line thatâ€™s rich with detail. Itâ€™s an important read in our modern, multicultural world.', 'Houghton Mifflin', '', '', '', '', '', '', '', '', '1', '', '', 1999, 198, 'pulitzer', NULL, 'interpreter-of-maladies.jpeg', 30),
('The Diary of a Young Girl', 'Anne Frank', 'Reading The Diary of a Young Girl by Anne Frank is a rite of passage for many adolescents and young adults, but older adults will find a lot to appreciate in this young womanâ€™s wise words. Written during World War II as Nazis carried out their campaign of death and destruction, this journal is a day-by-day accounting of what life was like when a family was forced into hiding. Frankâ€™s humanity and grace in light of her circumstances are inspiring and heartbreaking at once. Itâ€™s a deeply moving nonfiction book for kids and adults alike.', 'Contact Publishing', '', '', '', '', '', '', '', '', '', '1', '1', 1947, 304, '', NULL, 'the-diary-of-a-young-girl.jpeg', 31),
('Lolita', 'Vladimir Nabokov', 'Vladimir Nabokovâ€™s Lolita may have first gained fame and notoriety for its infamous accounting of the protagonistâ€™s unnatural (and, many argue, predatory) erotic predilections, but its staying power rests squarely on the breathtaking story that belies the most controversial elements. Itâ€™s a requiem about love (and, yes, lust), in all its maddening forms.', 'Olympia Press', '', '', '', '', '', '', '', '', '1', '', '', 1955, 336, '', 'https://www.youtube.com/watch?v=vaO_L0n0zhc', 'lolita.jpeg', 32),
('Love Medicine', 'Louise Eldrich', 'Shakespeareâ€™s Montagues and Capulets can barely hold a handle to Louise Eldrichâ€™s Kashpaws and Lamartines. Love Medicine, a dazzling work of storytelling that takes place on and around a North Dakota Ojibwe reservation, shares the intertwined fates of two multigenerational families. Themes of injustice, betrayal, magic, and mystique surround a beautiful story that, in the end, is all about the power of love. For more entertainment from this era, turn on one of these fantastic â€™80s movies.', 'Holt, Rinehart, and Winston HarperCollins', '', '', '', '', '', '', '', '', '1', '', '', 1984, 367, 'national', NULL, 'love-medicine.jpeg', 33),
('Middlesex', 'Jeffrey Eugenides', 'Calliope Helen Stephanides was born in Detroit in 1960, the heyday of Motor City, to a Greek American family who lived a quintessentially suburban American life. Moving out of the city, Calliope is faced with the realization that sheâ€™s not like other girls. It takes uncovering a family secret (and an astonishing genetic history) to understand why. Middlesex made waves as an audacious story of sexuality that transcends stereotypes of gender, sex, and identity.', 'Farrar, Straus and Giroux', '', '', '', '', '', '', '', '', '1', '', '', 2002, 544, 'pulitzer', NULL, 'middlesex.jpeg', 34),
('Midnight Children', 'Salman Rushdie', 'Saleem Sinai was born at midnight on August 15, 1947. That is precisely the moment India became an independent state. Greeted with fireworks and fanfare, Sinai and 1,000 other â€œmidnightâ€™s childrenâ€ across India soon find their health, well-being, thoughts, and capabilities are preternaturally linked to one anotherâ€”and to their countryâ€™s national affairs, health, and power. In this magical realism novel, Salman Rushdie offers a timeless, enchanting story of family, heritage, and duty.', 'Jonathan Cape', '', '', '', '', '', '1', '', '', '1', '', '', 1981, 446, '', 'https://www.youtube.com/watch?v=Y6T35sFH_as', 'midnights-children.jpeg', 35),
('And Then There Were None', 'Agatha Christie', 'In a world rife with paperback mysteries and e-books, Agatha Christie remains one of the most popular, well-known mystery writers of all time. In her vast collection, And Then There Were None frequently rises to the top. Itâ€™s a classic whodunit. Ten strangers are invited to a remote mansion on a desolate island. Once theyâ€™ve arrived, each guest is accused of murder. So what really happened? And who is responsible? Pick up a copy to find out; it makes a great summer read, after all.', 'Collins Crime Club', '', '', '', '1', '', '', '', '', '', '', '', 1939, 300, '', 'https://www.youtube.com/watch?v=srOKFpdNOSk', 'and-then-there-were-none.jpeg', 36),
('Homegoing', 'Yaa Gyasi', 'Donâ€™t miss this historical fiction masterpiece that also landed on our list of the best books by Black authors. Readers will fall in love with the riveting story of two sisters with very different fates. One was kidnapped and enslaved. The other married an Englishman and built a life of wealth and prestige. The award-winning book (it won the Hemingway Foundation PEN Award and the American Book Award, among others) delves deep into generational trauma and colonization. It is a must-read for modern bibliophiles.', 'Penguin Random House', '', '', '', '', '', '1', '', '', '', '', '', 2016, 320, '', NULL, 'homegoing.jpeg', 37),
('The Amazing Adventures of Kavalier & Clay', 'Michael Chabon', 'You donâ€™t need pirates and boats to have a swashbuckling thriller of a book. In The Amazing Adventures of Kavalier & Clay, the lives and adventures of a curious and meddlesome pair of cousins are explored in exuberant detail. Cousins Joe Kavalier and Sammy Clay swing through the glittering streets of preâ€“World War II Brooklyn, spinning up comic books to feed Americaâ€™s growing craze. Their hero, Escapist, fights fascists and falls hard for Luna Moth, an ethereal, mysterious, and desirous paramour. Their livesâ€”and their careersâ€”are equally bright and fanciful. The book received an incredible amount of praise from readers and critics. It also became a New York Times best seller.', 'Random House', '', '', '', '', '', '1', '', '', '', '', '', 2000, 639, 'pulitzer', NULL, 'the-amazing-adventures-of-kavalier-clay.jpeg', 38),
('The Brief Wondrous Life of Oscar Wao', 'Junot Diaz', 'Oscar Wao is a pleasant nerd living in New Jersey, far removed from the comforts and traditions of the Dominican Republic his mother knows and loves. Wao wants nothing more than to find loveâ€”and to be the Dominican J.R.R. Tolkien. His quest for both plunges readers into mythologies of family curses, immigrant journeys, and the American experience. The Brief Wondrous Life of Oscar Wao is a page-turner thatâ€™ll find a home with anyone who lusts for love and the human experience.', 'Riverhead', '', '', '', '', '', '', '', '', '1', '', '', 2007, 352, 'pulitzer', NULL, 'the-brief-wondrous-life-of-oscar-wao.jpeg', 39),
('The Catcher in the Rye', 'J.D. Salinger', 'Originally meant for an adult audience, The Catcher in the Rye has become a favorite among adolescent readers and high school literature teachers. The theme of teenage angst and alienation imbue a story of rebellion as the protagonist, Holden Caulfield, looks for acceptance, recognition, and appreciation. Like so many teenagers, Caulfield finds himself facing the decision to leave everything behind, only to face the realization that perhaps his life isnâ€™t as dreadful as it seems. For something totally different, take a bite out of one of these vampire books.', 'Little, Brown', '', '', '', '', '', '', '', '', '1', '', '', 1951, 234, '', NULL, 'the-catcher-in-the-rye.jpeg', 40),
('The Color of Water: A Black Manâ€™s Tribute to His White Mother', 'James McBride', 'â€œGod is the color of water,â€ Ruth McBride taught her children, expressing her belief that Godâ€™s blessings, values, and grace rise above skin color and race. McBride, a â€œlight-skinnedâ€ mother to 12 Black children, brought up her kids in the all-Black projects of Red Hook, Brooklyn, sending them to Jewish schools, shuttling them to free cultural events, and eventually shepherding all of them through college and beyond. But McBrideâ€™s son, James, discovers that sheâ€™s actually a White woman who was born in Poland, and he unearths the many painful reasons she has for hiding from that truth in this powerful, National Book Awardâ€“winning memoir.', 'Penguin Group', '', '', '', '', '', '', '', '', '', '1', '1', 1995, 301, 'national', NULL, 'the-color-of-water-a-black-mans-tribute-to-his-white-mother.jpeg', 41),
('The Giver', 'Lois Lowry', 'Jonas lives in a Utopian world. Everyoneâ€™s role is clear, and everyone fulfills those roles blissfully. Life is a set path thatâ€™s followed precisely. When he turns 12, however, Jonas begins to learn the reason his world is very fragile. The Giver is a dystopian story about what youâ€™re willing to give upâ€”and what youâ€™re notâ€”to live a life thatâ€™s free of emotions, pain, and suffering.', 'Houghton Mifflin', '', '1', '', '', '', '', '', '', '', '', '', 1993, 208, 'newbery', 'https://www.youtube.com/watch?v=uxFJvlWqphM', 'the-giver.jpeg', 42),
('The Night Watchmen', 'Louise Erdrich', 'The Night Watchmen snagged the top spot on our list of the best Native American books for a reason. Based on Louise Erdrichâ€™s grandfatherâ€™s life, the story is about one Native American night watchman who fights for his right to land and identity in the United States. The book brims with beautiful sentences and a riveting story, but it also received critical acclaim for its important themes and depiction of cultural identity.', 'HarperCollins', '', '', '', '', '', '1', '', '', '', '', '', 2020, 464, 'pulitzer', NULL, 'the-night-watchmen.jpeg', 43),
('Never Let Me Go', 'Kazuo Ishiguro', 'Kazuo Ishiguro is on our list of contemporary writers you should have read by now. He won the 2017 Nobel Prize in Literature, and his 2005 publication of Never Let Me Go is at least one reason why. The science fiction story centers on cloned humans living in a boarding school who await their future as forced organ donors. But, of course, clones are humans, too, and the studentsâ€™ lives intertwine with friendship, love, and lust even as they grow more entrapped by their inevitable role in society. This is a must-read for its portrayal of enduring friendship, its questions about medical science, and its masterful writing.', 'Faber and Faber', '', '1', '', '', '', '', '', '', '', '', '', 2005, 288, 'nobel', 'https://www.youtube.com/watch?v=sXiRZhDEo8A', 'never-let-me-go.jpg', 44),
('Between the World and Me', 'Ta-Nehisi Coates', 'Our list of the best books of all time filled up quickly with fiction. But there are a few nonfiction tomes, including Ta-Nehisi Coatesâ€™ bible for the Black Lives Matter movement, that cannot be left out. This important book about racism offers a clear understanding of how Black men and women have been ostracized and exploited by formal systems throughout history. What makes the book even more compelling is how it mashes together history and modern memoir. The result is a bold, clear call to upend current racist systems and strive for a truly fair society.', 'Spiegel & Grau', '', '', '', '', '', '', '', '', '', '1', '1', 2015, 176, 'national', 'https://www.youtube.com/watch?v=6ZbKLlVrrjQ', 'between-the-world-and-me.jpeg', 45),
('The Year of Magical Thinking', 'Joan Didion', 'One of lifeâ€™s truest axioms is that there will be good times and there will be bad times. If you can relate to both, or even if you canâ€™t, Joan Didionâ€™s The Year of Magical Thinking is a heart-wrenching story of a marriage, a family, a relationship, and a life thatâ€™s good, great, bad, awful, and everything in between. And in the end, isnâ€™t that just a story about life?', 'Knopf', '', '', '', '', '', '', '', '', '', '', '1', 2005, 240, 'national', NULL, 'the-year-of-magical-thinking.jpeg', 46),
('White Teeth', 'Zadie Smith', 'Zadie Smithâ€™s debut novel tells the tale of two women whose lives are forever changed by what they experienced together during World War II. This fast-paced historical fiction story covers a lot of ground: race, ethnicity, religion, class struggles, and more. The powerhouse novel landed on our list for its overwhelming praise from readers and critics alike.', 'Hamish Hamilton Salamandra', '', '', '', '', '', '', '', '', '1', '', '', 2008, 480, '', NULL, 'white-teeth.jpeg', 47),
('The Color Purple', 'Alice Walker', 'When Alice Walkerâ€™s award-winning novel was first published in the 1980s, it was quickly censored. The author has said that most of the criticisms come from those who never even cracked open the book. So, whatâ€™s all the hubbub about? The Color Purple tells the story of a Black teen in 1930s rural Georgia. It centers around Celie, who writes about her day-to-day life in letters addressed to God. Yes, the book contains sexual themes, profanity, and violence. But its powerful prose has won awards, resulted in film and musical adaptations, and earned a spot on â€œbest ofâ€ lists everywhere.', 'Harcourt Brace Jovanovich', '', '', '', '', '', '', '', '', '1', '', '', 1982, 245, 'pulitzer', 'https://www.youtube.com/watch?v=HzGrDgu08r8', 'the-color-purple.jpeg', 48),
('Charlotte\'s Web', 'E.B White', 'Youâ€™re never too old to visit with Charlotte, Wilbur, and Templeton. This heartwarming tale of friendship and dedication follows young Wilbur, a runt of a pig, as heâ€™s spared from one death but subsequently sent to another almost-certain death. Desperate to help the petite porker, Charlotte, a barn spider, hatches a plan that proves genius and life-altering for young Wilbur. Charlotteâ€™s Web remains a touching, great read for families.', 'HarperCollins', '', '', '', '', '', '', '1', '', '', '', '', 1952, 192, 'newbery', 'https://www.youtube.com/watch?v=YSC7NrzDt24', 'Charlottes-Web.jpeg', 54),
('The Song of Achilles', 'Madeline Miller', 'Achilles, \"the best of all the Greeks,\" son of the cruel sea goddess Thetis and the legendary king Peleus, is strong, swift, and beautiful, irresistible to all who meet him. Patroclus is an awkward young prince, exiled from his homeland after an act of shocking violence. Brought together by chance, they forge an inseparable bond, despite risking the gods\' wrath.\r\n\r\nThey are trained by the centaur Chiron in the arts of war and medicine, but when word comes that Helen of Sparta has been kidnapped, all the heroes of Greece are called upon to lay siege to Troy in her name. Seduced by the promise of a glorious destiny, Achilles joins their cause, and torn between love and fear for his friend, Patroclus follows. Little do they know that the cruel Fates will test them both as never before and demand a terrible sacrifice.', 'HarperCollins', '', '', '', '', '1', '', '1', '', '', '', '', 2011, 378, 'women', NULL, 'a-song-of-achilles.jpeg', 55),
('On Beauty', 'Zadie Smith', 'Howard Belsey, a Rembrandt scholar who doesn\'t like Rembrandt, is an Englishman abroad and a long-suffering professor at Wellington, a liberal New England arts college. He has been married for thirty years to Kiki, an American woman who no longer resembles the sexy activist she once was. Their three children passionately pursue their own paths: Levi quests after authentic blackness, Zora believes that intellectuals can redeem everybody, and Jerome struggles to be a believer in a family of strict atheists. Faced with the oppressive enthusiasms of his children, Howard feels that the first two acts of his life are over and he has no clear plans for the finale. Or the encore.', 'Hamish Hamilton', '', '', '', '', '', '', '', '', '', '', '', 2005, 445, 'women', NULL, 'on-beauty.jpeg', 56),
('Flights', 'Olga Tokarczuk', 'From the incomparably original Polish writer Olga Tokarczuk, Flights interweaves reflections on travel with an in-depth exploration of the human body, broaching life, death, motion, and migration. Chopinâ€™s heart is carried back to Warsaw in secret by his adoring sister. A woman must return to her native Poland in order to poison her terminally ill high school sweetheart, and a young man slowly descends into madness when his wife and child mysteriously vanish during a vacation and just as suddenly reappear. Through these brilliantly imagined characters and stories, interwoven with haunting, playful, and revelatory meditations, Flights explores what it means to be a traveler, a wanderer, a body in motion not only through space but through time. Where are you from? Where are you coming in from? Where are you going? we call to the traveler. Enchanting, unsettling, and wholly original, Flights is a master storytellerâ€™s answer.', 'Wydawnictwo Literackie', '', '', '', '', '', '', '', '', '1', '', '', 2007, 416, 'booker', NULL, 'flights.jpeg', 57);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `top_books_rd`
--
ALTER TABLE `top_books_rd`
  ADD PRIMARY KEY (`book_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `top_books_rd`
--
ALTER TABLE `top_books_rd`
  MODIFY `book_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=58;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
